# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20160125_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='score',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
