# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20160125_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log_time',
            field=models.DateTimeField(verbose_name='test'),
        ),
    ]
