# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20160125_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='pub_time',
            field=models.DateTimeField(verbose_name='show time'),
        ),
        migrations.AlterField(
            model_name='score',
            name='update_time',
            field=models.DateTimeField(verbose_name='score time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='log_time',
            field=models.DateTimeField(verbose_name='log time'),
        ),
    ]
